
export const oneRmList = [
    {id:0, oneRm:'Clean'},
    {id:1, oneRm:'Power Clean'},
    {id:2, oneRm:'Clean and Jerk'},
    {id:3, oneRm:'Hang Clean'},
    {id:4, oneRm:'Hang Power Clean'},
    {id:5, oneRm:'Snatch'},
    {id:6, oneRm:'Power Snatch'},
    {id:7, oneRm:'Hang Snatch'},
    {id:8, oneRm:'Hang Power Snatch'},
    {id:9, oneRm:'Push Jerk'},
    {id:10, oneRm:'Split Jerk'},
    {id:11, oneRm:'Push Press'},
    {id:12, oneRm:'Shoulder Press'},
    {id:13, oneRm:'Bench Press'},
    {id:14, oneRm:'Thruster'},
    {id:15, oneRm:'Back Squat'},
    {id:16, oneRm:'Front Squat'},
    {id:17, oneRm:'Overhead Squat'},
    {id:18, oneRm:'Deadlift'}
];
export const namedWodList = [
    {id:0, namedWod:'Murph'},
    {id:1, namedWod:'Fran'},
    {id:2, namedWod:'Cindy'},
    {id:3, namedWod:'Nick'},
    {id:4, namedWod:'Chelsea'},
    {id:5, namedWod:'Angie'},
    {id:6, namedWod:'Helen'},
    {id:8, namedWod:'The Longest Mile'},
    {id:9, namedWod:'Zeus'},
    {id:10, namedWod:'The Glen'},
    {id:11, namedWod:'The Chief'},
    {id:12, namedWod:'Filthy Fifty'},
    {id:13, namedWod:'Annie'},
    {id:14, namedWod:'Barbara'},
    {id:15, namedWod:'Diane'},
    {id:16, namedWod:'Elizabeth'},
    {id:17, namedWod:'Frelen'},
    {id:18, namedWod:'Isabel'},
    {id:19, namedWod:'Jackie'},
    {id:20, namedWod:'Karen'},
    {id:21, namedWod:'Kelly'},
    {id:22, namedWod:'Linda'},
    {id:23, namedWod:'Lynne'},
    {id:24, namedWod:'Mary'},
    {id:25, namedWod:'Nancy'},
    {id:26, namedWod:'Nicole'},
    {id:27, namedWod:'Nate'},
    {id:28, namedWod:'JT'},
    {id:29, namedWod:'Nuts'},
    {id:30, namedWod:'Danny'},
    {id:31, namedWod:'Roy'},
    {id:32, namedWod:'Arnie'},
    {id:33, namedWod:'Luce'},
    {id:34, namedWod:'Jag 28'},
    {id:35, namedWod:'Tom'}
];