
export const oneRmList = [
    {id:0, oneRm:'Clean'},
    {id:1, oneRm:'Power Clean'},
    {id:2, oneRm:'Clean and Jerk'},
    {id:3, oneRm:'Hang Clean'},
    {id:4, oneRm:'Hang Power Clean'},
    {id:5, oneRm:'Snatch'},
    {id:6, oneRm:'Power Snatch'},
    {id:7, oneRm:'Hang Snatch'},
    {id:8, oneRm:'Hang Power Snatch'},
    {id:9, oneRm:'Push Jerk'},
    {id:10, oneRm:'Split Jerk'},
    {id:11, oneRm:'Push Press'},
    {id:12, oneRm:'Shoulder Press'},
    {id:13, oneRm:'Bench Press'},
    {id:14, oneRm:'Thruster'},
    {id:15, oneRm:'Back Squat'},
    {id:16, oneRm:'Front Squat'},
    {id:17, oneRm:'Overhead Squat'},
    {id:18, oneRm:'Deadlift'}
];
export const namedWodList = [
    {id:0, namedWod:'Murph', namedWodContents:'For Time\n 1 mile Run\n 100 Pull-Ups\n 200 Push-Ups\n 300 Air Squats\n 1 mile Run All with a Weight Vest (20/14 lb)'},
    {id:1, namedWod:'Fran', namedWodContents:'21-15-9 Reps For Time\n Thrusters (95/65 lb)\n Pull-Ups'},
    {id:2, namedWod:'Cindy', namedWodContents:'AMRAP in 20 minutes\n 5 Pull-Ups\n 10 Push-Ups\n 15 Air Squats'},
    {id:3, namedWod:'Nick', namedWodContents:'12 Rounds For Time\n 10 Dumbbell Hang Squat Cleans (2x45/35 lb)\n 6 Handstand Push-Ups on Dumbbells'},
    {id:4, namedWod:'Chelsea', namedWodContents:'EMOM for 30 minutes\n 5 Pull-Ups\n 10 Push-Ups\n 15 Air Squats'},
    {id:5, namedWod:'Angie', namedWodContents:'For Time\n 100 Pull-Ups\n 100 Push-Ups\n 100 Sit-Ups\n 100 Air Squats'},
    {id:6, namedWod:'Helen', namedWodContents:'3 Rounds For Time\n 400 meter Run\n 21 Kettlebell Swings (1.5/1 pood)\n 12 Pull-Ups'},
    {id:8, namedWod:'The Longest Mile', namedWodContents:'4 Rounds for Time\n 10 Burpees\n 100 meter Run\n 10 Air Squats\n 100 meter Run\n 10 Push-Ups\n 100 meter Run\n 10 Sit-Ups\n 100 meter Run'},
    {id:9, namedWod:'Zeus', namedWodContents:'3 Rounds For Time\n 30 Wall Ball Shots (20/14 lb)\n 30 Sumo Deadlift High-Pull (75/55 lb)\n 30 Box Jump (20 in)\n 30 Push Presses (75/55 lb)\n 30 calorie Row\n 30 Push-Ups\n 10 Back Squats (Bodyweight)'},
    {id:10, namedWod:'The Glen', namedWodContents:'For Time\n 30 Clean-and-Jerks (135/95 lb)\n 1 mile Run\n 10 Rope Climbs (15 ft)\n 1 mile Run\n 100 Burpees'},
    {id:11, namedWod:'The Chief', namedWodContents:'Five 3-minute AMRAPs in 19 minutes\n AMRAP in 3 minutes\n 3 Power Cleans (135/95 lbs)\n 6 Push-Ups\n 9 Air Squats\n Then Rest 1 minute Repeat 5 times'},
    {id:12, namedWod:'Filthy Fifty', namedWodContents:'For Time\n 50 Box Jumps (24/20 in)\n 50 Jumping Pull-Ups\n 50 Kettlebell Swings (1/.75 pood)\n 50 Walking Lunge Steps\n 50 Knees-to-Elbows\n 50 Push Presses (45/35 lb)\n 50 Back Extensions\n 50 Wall Ball Shots (20/14 lb)\n 50 Burpees\n 50 Double-Unders'},
    {id:13, namedWod:'Annie', namedWodContents:'50-40-30-20-10 Reps For Time\n Double-Unders Sit-Ups'},
    {id:14, namedWod:'Barbara', namedWodContents:'5 Rounds For Time\n 20 Pull-Ups\n 30 Push-Ups\n 40 Sit-Ups\n 50 Air Squats\n 3 minutes Rest'},
    {id:15, namedWod:'Diane', namedWodContents:'21-15-9 Reps For Time\n Deadlifts (225/155 lb)\n Handstand Push-Ups'},
    {id:16, namedWod:'Elizabeth', namedWodContents:'21-15-9 Reps For Time\n Cleans (135/95 lb)\n Ring Dips'},
    {id:17, namedWod:'Frelen', namedWodContents:'5 Rounds for Time\n 800 meter Run\n 15 Dumbbell Thrusters (45/35 lb)\n 15 Pull-Ups'},
    {id:18, namedWod:'Isabel', namedWodContents:'For Time 30\n Snatches (135/95 lb)'},
    {id:19, namedWod:'Jackie', namedWodContents:'For Time\n 1,000 meter Row\n 50 Thrusters (45/35 lb bar)\n 30 Pull-Ups'},
    {id:20, namedWod:'Karen', namedWodContents:'For Time\n 150 Wall Ball Shots (20/14 lb, 10/9 ft)'},
    {id:21, namedWod:'Kelly', namedWodContents:'5 Rounds For Time\n 400 meter Run\n 30 Box Jumps (24/20 in)\n 30 Wall Ball Shots (20/14 lb)'},
    {id:22, namedWod:'Linda', namedWodContents:'10-9-8-7-6-5-4-3-2-1 Reps, For Time\n Deadlift (1½ bodyweight)\n Bench Press (bodyweight)\n Clean (¾ bodyweight)'},
    {id:23, namedWod:'Lynne', namedWodContents:'As Many Repetitions as Possible in 5 Rounds of:\n Max Bench Press (bodyweight)\n Max Pull-Ups'},
    {id:24, namedWod:'Mary', namedWodContents:'AMRAP in 20 minutes\n 5 Handstand Push-Ups\n 10 Pistols (alternating legs)\n 15 Pull-Ups'},
    {id:25, namedWod:'Nancy', namedWodContents:'5 Rounds For Time\n 400 meter Run\n 15 Overhead Squats (95/65 lb)'},
    {id:26, namedWod:'Nicole', namedWodContents:'AMRAP in 20 minutes\n 400 meter Run\n Max Pull-Ups'},
    {id:27, namedWod:'Nate', namedWodContents:'AMRAP in 20 minutes\n 2 Muscle-Ups\n 4 Handstand Push-Ups\n 8 Kettlebell Swings (2/1.5 pood)'},
    {id:28, namedWod:'JT', namedWodContents:'21-15-9 Reps For Time\n Handstand Push-Ups\n Ring Dips\n Push-Ups'},
    {id:29, namedWod:'Nuts', namedWodContents:'For Time\n 10 Handstand Push-Ups\n 15 Deadlifts (250/175 lb)\n 25 Box Jumps (30/24 in)\n 50 Pull-Ups\n 100 Wall Ball Shots (20/14 lb)\n 200 Double-Unders\n 400 meter Run (with 45/35 lb plate)'},
    {id:30, namedWod:'Danny', namedWodContents:'AMRAP in 20 minutes\n 30 Box Jumps (24/20 in)\n 20 Push Presses (115/75 lb)\n 30 Pull-Ups'},
    {id:31, namedWod:'Roy', namedWodContents:'5 Rounds For Time\n 15 Deadlifts (225/155 lb)\n 20 Box Jumps (24/20 in)\n 25 Pull-Ups'},
    {id:32, namedWod:'Arnie', namedWodContents:'For Time\n 21 Turkish Get-Ups,\n Right Arm 50 Kettlebell Swings\n 21 Overhead Squats,\n Left Arm 50 Kettlebell Swings\n 21 Overhead Squats,\n Right Arm 50 Kettlebell Swings\n 21 Turkish Get-Ups,\n Left Arm Use a single Kettlebell (2/1.5 pood)'},
    {id:33, namedWod:'Luce', namedWodContents:'3 Rounds For Time\n 1,000 meter Run\n 10 Muscle-Ups\n 100 Air Squats\n Wear a Weight Vest (20/14 lb)'},
    {id:34, namedWod:'Jag 28', namedWodContents:'For Time\n 800 meter Run\n 28 Kettlebell Swings (2/1.5 pood)\n 28 Strict Pull-Ups\n 28 Kettlebell Clean-and-Jerks (2 x 2/1.5 pood)\n 28 Strict Pull-Ups\n 800 meter Run'},
    {id:35, namedWod:'Tom', namedWodContents:'AMRAP in 25 minutes\n 7 Muscle-Ups\n 11 Thrusters (155/105 lb)\n 14 Toes-to-Bar'}
];